import numpy as n
a=n.arange(1,11).reshape(2,-1)
b=n.arange(11,21).reshape(2,-1)
print(a)
print('------------')
print(b)
print('------------')
c=n.stack((a,b))
print(c)
print('------------')
print(c[0])
print(f'row wise:\n {n.stack((a,b),axis=0)}')
print('------------')
print(f'col wise:\n {n.stack((a,b),axis=1)}')